steps:
  # 1. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-analytics:$BRANCH_NAME'
      - '-t'
      - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-analytics:latest'
      - '.'

  # 2. Push Docker Images to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-analytics:$BRANCH_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-analytics:latest']

  # 3. Trigger Remote SSH Deployment on VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh bashasoft304@ems-backend-vm \
          --zone=us-central1-a \
          --command="cd ~/ems-deployment && docker-compose pull && docker-compose down && docker-compose up -d"

images:
  - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-analytics:$BRANCH_NAME'
  - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/ems-analytics:latest'

options:
  logging: CLOUD_LOGGING_ONLY
